version: "3.8"

services:
  database:
    image: postgres:16.0
    container_name: andromeda_database
    environment:
      - POSTGRES_USER=andromeda
      - POSTGRES_PASSWORD=andromeda
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 5s
